<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup Label="Project Settings">
		<TargetFrameworks>net8.0;net9.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup Label="Package References NET 8.0" Condition="$(TargetFramework) == 'net8.0'">
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.11">
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
	</ItemGroup>
	
	<ItemGroup Label="Package References NET 9.0" Condition="$(TargetFramework) == 'net9.0'">
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0">
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup Label="Project References">
		<ProjectReference Include="..\..\BenBurgers.InternationalStandards.Iso.EFCore.SqlServer\BenBurgers.InternationalStandards.Iso.EFCore.SqlServer.csproj" />
	</ItemGroup>

</Project>
